In [1]:
from config import gkey
from config import weatherkey
from citipy import citipy
import numpy as np
import pandas as pd
import requests
import json
from pprint import pprint
from matplotlib import pyplot as plt
from scipy import stats
import os
import gmaps

In [2]:
# read in WeatherPy dataframe
csv_path = '../WeatherPy/Output/'
csv_file = 'City Weather Data.csv'
weather_df = pd.DataFrame(pd.read_csv(csv_path + csv_file))
weather_df

,Unnamed: 0,City,Country,Lattitude,Longitude,Temperature C,Temperature F,Humidity %,Cloudiness %,Wind Speed (mph)
0,0,Jian,CN,27.1172,114.9793,12.66,56.588,83.0,100.0,8.7808
1,1,French Harbor,HN,16.3500,-86.4333,24.04,77.072,99.0,9.0,10.9760
2,2,Yellowknife,CA,62.4560,-114.3525,-11.85,12.470,79.0,90.0,14.9856
3,3,Cairns,AU,-16.9167,145.7667,27.15,82.670,69.0,75.0,5.7568
4,4,Ushuaia,AR,-54.8000,-68.3000,2.15,37.670,93.0,75.0,20.7424
...,...,...,...,...,...,...,...,...,...,...
495,495,Kamthi,IN,21.2333,79.2000,34.15,95.270,26.0,40.0,3.4496
496,496,Nouadhibou,MR,20.9310,-17.0347,17.15,64.670,67.0,0.0,21.8848
497,497,Linqiong,CN,30.4159,103.4609,15.15,61.070,54.0,0.0,8.9600
498,498,Olafsvik,IS,64.8945,-23.7142,3.53,40.154,77.0,100.0,20.9216
499,499,Saint-Joseph,RE,-21.3667,55.6167,30.15,88.070,58.0,0.0,26.4992

In [3]:
# Drop left column, cleanup
weather_df.drop(weather_df.columns[[0]], axis=1, inplace=True)
weather_df

,City,Country,Lattitude,Longitude,Temperature C,Temperature F,Humidity %,Cloudiness %,Wind Speed (mph)
0,Jian,CN,27.1172,114.9793,12.66,56.588,83.0,100.0,8.7808
1,French Harbor,HN,16.3500,-86.4333,24.04,77.072,99.0,9.0,10.9760
2,Yellowknife,CA,62.4560,-114.3525,-11.85,12.470,79.0,90.0,14.9856
3,Cairns,AU,-16.9167,145.7667,27.15,82.670,69.0,75.0,5.7568
4,Ushuaia,AR,-54.8000,-68.3000,2.15,37.670,93.0,75.0,20.7424
...,...,...,...,...,...,...,...,...,...
495,Kamthi,IN,21.2333,79.2000,34.15,95.270,26.0,40.0,3.4496
496,Nouadhibou,MR,20.9310,-17.0347,17.15,64.670,67.0,0.0,21.8848
497,Linqiong,CN,30.4159,103.4609,15.15,61.070,54.0,0.0,8.9600
498,Olafsvik,IS,64.8945,-23.7142,3.53,40.154,77.0,100.0,20.9216
499,Saint-Joseph,RE,-21.3667,55.6167,30.15,88.070,58.0,0.0,26.4992

In [4]:
# Create Heat Map

locations = weather_df[["Lattitude", "Longitude"]].astype(float)
humidity = weather_df["Humidity %"].astype(float)

humidity_map = gmaps.figure()
heat_layer = gmaps.heatmap_layer(
    locations, 
    weights=humidity,                                
    dissipating=False, 
    max_intensity=500,
    point_radius = 6)

humidity_map.add_layer(heat_layer)
humidity_map

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Create Ideal Holiday Weather Conditions Dataframe
IdealHoliday_df = weather_df.loc[(weather_df['Temperature C'] > 24) & (weather_df['Temperature C'] < 32) & (weather_df['Humidity %'] < 70) & (weather_df['Cloudiness %'] < 20)]
IdealHoliday_df

,City,Country,Lattitude,Longitude,Temperature C,Temperature F,Humidity %,Cloudiness %,Wind Speed (mph)
5,Saint-Philippe,RE,-21.3585,55.7679,30.15,88.070,62.0,0.0,28.8064
21,Busselton,AU,-33.6500,115.3333,31.26,90.068,40.0,8.0,3.0016
26,Esperance,AU,-33.8667,121.9000,27.15,82.670,47.0,0.0,16.1280
42,Buraydah,SA,26.3260,43.9750,26.15,80.870,27.0,0.0,10.3712
84,Riyadh,SA,24.6877,46.7219,28.15,84.470,10.0,0.0,12.6784
119,Kismayo,SO,-0.3582,42.5454,30.45,88.610,58.0,0.0,11.6480
129,Luderitz,NaN,-26.6481,15.1594,25.56,79.808,48.0,13.0,23.6320
130,Namibe,AO,-15.1961,12.1522,25.15,79.070,69.0,0.0,7.5264
193,Mopipi,BW,-21.1833,24.8833,31.34,90.212,29.0,0.0,14.2688
233,Tabuk,SA,28.3833,36.5833,26.15,80.870,13.0,0.0,3.7184
239,Waddan,LY,29.1614,16.1390,26.48,81.464,17.0,0.0,3.2704
260,Veraval,IN,20.9000,70.3667,28.95,85.910,59.0,0.0,11.7600
383,Jinka,ET,5.6500,36.6500,29.26,86.468,40.0,7.0,4.5024
388,Bandarbeyla,SO,9.4942,50.8122,28.06,84.308,56.0,0.0,11.9392
439,Bayan,KW,29.3032,48.0488,27.15,82.670,14.0,0.0,18.4352
440,Awbari,LY,26.5921,12.7805,28.08,84.344,10.0,0.0,10.5952
441,Bhatkal,IN,13.9667,74.5667,30.83,89.294,55.0,0.0,8.4448
469,Sehithwa,BW,-20.4667,22.7167,31.63,90.734,32.0,0.0,9.6320
483,Tessalit,ML,20.1986,1.0114,31.65,90.770,6.0,0.0,6.3840
490,Le Port,RE,-20.9373,55.2919,30.15,88.070,58.0,0.0,24.1920
499,Saint-Joseph,RE,-21.3667,55.6167,30.15,88.070,58.0,0.0,26.4992

In [6]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="


for index, rows in IdealHoliday_df.iterrows():
    lat = str(rows['Lattitude'])
    long = str(rows['Longitude'])
    city = rows['City']
    full_url = base_url + lat + "," + long + "&" + "rankby=prominence&" + 'keyword=hotel&' + 'radius=5000&' + 'type=hotel&' + 'key=' + gkey
    response = requests.get(full_url).json()
    try:
        hotel = response["results"][0]['name']
        IdealHoliday_df.at[index, 'Hotel']  = hotel
        lat = response["results"][0]['geometry']['location']['lat']
        IdealHoliday_df.at[index, 'HotelLat']  = lat
        long = response["results"][0]['geometry']['location']['lng']
        IdealHoliday_df.at[index, 'HotelLong']  = long
        print('Found a hotel in ' + city + ': ' + hotel)
    except:
        IdealHoliday_df.at[index, 'Hotel']  = 'None Found'
        print(city + 'sucks. No hotel. Sorry!')

IdealHoliday_df

C:\Users\sharp\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\sharp\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Found a hotel in Saint-Philippe: Les Embruns Du Baril
Found a hotel in Busselton: The Sebel Busselton
Found a hotel in Esperance: Esperance Chalet Village
Found a hotel in Buraydah: فندق تاورز HOTELTOWERS
Found a hotel in Riyadh: Centro Olaya
Found a hotel in Kismayo: Gobsoor Hotel
Found a hotel in Luderitz: LÜDERITZ NEST HOTEL
Found a hotel in Namibe: iu Hotel Namibe
Mopipisucks. No hotel. Sorry!
Found a hotel in Tabuk: Banan hotel
Found a hotel in Waddan: بشير التاجوري
Found a hotel in Veraval: Sarovar Portico Somnath
Jinkasucks. No hotel. Sorry!
Found a hotel in Bandarbeyla: JABIR HOTEL
Found a hotel in Bayan: Kuwait Palace Hotel
Found a hotel in Awbari: فندق أوباري
Found a hotel in Bhatkal: Hotel Kola Paradise
Found a hotel in Sehithwa: MONLEK GUEST HOUSE
Tessalitsucks. No hotel. Sorry!
Found a hotel in Le Port: Lodge Roche Tamarin & Spa Village Nature
Found a hotel in Saint-Joseph: Village Sauvage

,City,Country,Lattitude,Longitude,Temperature C,Temperature F,Humidity %,Cloudiness %,Wind Speed (mph),Hotel,HotelLat,HotelLong
5,Saint-Philippe,RE,-21.3585,55.7679,30.15,88.070,62.0,0.0,28.8064,Les Embruns Du Baril,-21.369201,55.727949
21,Busselton,AU,-33.6500,115.3333,31.26,90.068,40.0,8.0,3.0016,The Sebel Busselton,-33.659693,115.278613
26,Esperance,AU,-33.8667,121.9000,27.15,82.670,47.0,0.0,16.1280,Esperance Chalet Village,-33.825844,121.929558
42,Buraydah,SA,26.3260,43.9750,26.15,80.870,27.0,0.0,10.3712,فندق تاورز HOTELTOWERS,26.358644,43.951359
84,Riyadh,SA,24.6877,46.7219,28.15,84.470,10.0,0.0,12.6784,Centro Olaya,24.693169,46.684140
119,Kismayo,SO,-0.3582,42.5454,30.45,88.610,58.0,0.0,11.6480,Gobsoor Hotel,-0.357751,42.549262
129,Luderitz,NaN,-26.6481,15.1594,25.56,79.808,48.0,13.0,23.6320,LÜDERITZ NEST HOTEL,-26.652957,15.149620
130,Namibe,AO,-15.1961,12.1522,25.15,79.070,69.0,0.0,7.5264,iu Hotel Namibe,-15.190875,12.151276
193,Mopipi,BW,-21.1833,24.8833,31.34,90.212,29.0,0.0,14.2688,None Found,NaN,NaN
233,Tabuk,SA,28.3833,36.5833,26.15,80.870,13.0,0.0,3.7184,Banan hotel,28.420668,36.587375
239,Waddan,LY,29.1614,16.1390,26.48,81.464,17.0,0.0,3.2704,بشير التاجوري,29.166836,16.133611
260,Veraval,IN,20.9000,70.3667,28.95,85.910,59.0,0.0,11.7600,Sarovar Portico Somnath,20.899703,70.407510
383,Jinka,ET,5.6500,36.6500,29.26,86.468,40.0,7.0,4.5024,None Found,NaN,NaN
388,Bandarbeyla,SO,9.4942,50.8122,28.06,84.308,56.0,0.0,11.9392,JABIR HOTEL,9.497514,50.810636
439,Bayan,KW,29.3032,48.0488,27.15,82.670,14.0,0.0,18.4352,Kuwait Palace Hotel,29.344482,48.080902
440,Awbari,LY,26.5921,12.7805,28.08,84.344,10.0,0.0,10.5952,فندق أوباري,26.596688,12.766078
441,Bhatkal,IN,13.9667,74.5667,30.83,89.294,55.0,0.0,8.4448,Hotel Kola Paradise,13.995387,74.550240
469,Sehithwa,BW,-20.4667,22.7167,31.63,90.734,32.0,0.0,9.6320,MONLEK GUEST HOUSE,-20.478973,22.701008
483,Tessalit,ML,20.1986,1.0114,31.65,90.770,6.0,0.0,6.3840,None Found,NaN,NaN
490,Le Port,RE,-20.9373,55.2919,30.15,88.070,58.0,0.0,24.1920,Lodge Roche Tamarin & Spa Village Nature,-20.949848,55.341256
499,Saint-Joseph,RE,-21.3667,55.6167,30.15,88.070,58.0,0.0,26.4992,Village Sauvage,-21.379092,55.659249

In [7]:
marker_locations = IdealHoliday_df[IdealHoliday_df[['HotelLat', 'HotelLong']].notnull().all(1)]


marker_locations = marker_locations[['HotelLat','HotelLong']]
marker_locations

markers = gmaps.marker_layer(marker_locations)
humidity_map.add_layer(markers)
humidity_map

Figure(layout=FigureLayout(height='420px'))